[ESP32_OctopusLab_LAN_LoRa]
extends = esp32_base
board = esp32dev
platform_packages =
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.3
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
build_flags =
  ${esp32_base.build_flags}
  -I variants/octopuslab_lan_lora
  -D ESP32_OctopusLab_LAN_LoRa
  -D RADIO_CLASS=CustomSX1276
  -D WRAPPER_CLASS=CustomSX1276Wrapper
  -D ETH_PHY_TYPE=ETH_PHY_LAN8720
  -D LAN_PHY_ADDR=1
  -D LAN_POWER=-1
  -D LAN_MDC=23
  -D LAN_MDIO=18
  -D LAN_CLOCK_MODE=ETH_CLOCK_GPIO17_OUT
  -D P_LORA_DIO_0=34
  -D P_LORA_DIO_1=RADIOLIB_NC
  -D P_LORA_NSS=5
  -D P_LORA_RESET=RADIOLIB_NC
  -D P_LORA_SCLK=33
  -D P_LORA_MOSI=32
  -D P_LORA_MISO=35
  -D LORA_TX_POWER=20
  -D PIN_BOARD_SDA=2
  -D PIN_BOARD_SCL=16
build_src_filter = ${esp32_base.build_src_filter}
  +<../variants/octopuslab_lan_lora>
lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit SSD1306 @ ^2.5.13

[env:ESP32_OctopusLab_LAN_LoRa_repeater]
extends = ESP32_OctopusLab_LAN_LoRa
build_src_filter = ${ESP32_OctopusLab_LAN_LoRa.build_src_filter}
  +<../examples/simple_repeater/*.cpp>
build_flags =
  ${ESP32_OctopusLab_LAN_LoRa.build_flags}
  -D ADVERT_NAME='"OctopusLab LAN Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
  -D MESH_DEBUG=1
lib_deps =
  ${ESP32_OctopusLab_LAN_LoRa.lib_deps}
  ${esp32_ota.lib_deps}
